# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: scenic_obj_info.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import vector3d_pb2 as vector3d__pb2
import quaternion_pb2 as quaternion__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='scenic_obj_info.proto',
  package='scenic_obj_info_msgs.msgs',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=_b('\n\x15scenic_obj_info.proto\x12\x19scenic_obj_info_msgs.msgs\x1a\x0evector3d.proto\x1a\x10quaternion.proto\"\xcf\x01\n\x10ScenicObjectInfo\x12\'\n\x08position\x18\x01 \x02(\x0b\x32\x15.gazebo.msgs.Vector3d\x12,\n\x0borientation\x18\x02 \x02(\x0b\x32\x17.gazebo.msgs.Quaternion\x12*\n\x0b\x61ngVelocity\x18\x03 \x02(\x0b\x32\x15.gazebo.msgs.Vector3d\x12*\n\x0blinVelocity\x18\x04 \x02(\x0b\x32\x15.gazebo.msgs.Vector3d\x12\x0c\n\x04name\x18\x05 \x02(\t')
  ,
  dependencies=[vector3d__pb2.DESCRIPTOR,quaternion__pb2.DESCRIPTOR,])




_SCENICOBJECTINFO = _descriptor.Descriptor(
  name='ScenicObjectInfo',
  full_name='scenic_obj_info_msgs.msgs.ScenicObjectInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='position', full_name='scenic_obj_info_msgs.msgs.ScenicObjectInfo.position', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='orientation', full_name='scenic_obj_info_msgs.msgs.ScenicObjectInfo.orientation', index=1,
      number=2, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='angVelocity', full_name='scenic_obj_info_msgs.msgs.ScenicObjectInfo.angVelocity', index=2,
      number=3, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='linVelocity', full_name='scenic_obj_info_msgs.msgs.ScenicObjectInfo.linVelocity', index=3,
      number=4, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='name', full_name='scenic_obj_info_msgs.msgs.ScenicObjectInfo.name', index=4,
      number=5, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=87,
  serialized_end=294,
)

_SCENICOBJECTINFO.fields_by_name['position'].message_type = vector3d__pb2._VECTOR3D
_SCENICOBJECTINFO.fields_by_name['orientation'].message_type = quaternion__pb2._QUATERNION
_SCENICOBJECTINFO.fields_by_name['angVelocity'].message_type = vector3d__pb2._VECTOR3D
_SCENICOBJECTINFO.fields_by_name['linVelocity'].message_type = vector3d__pb2._VECTOR3D
DESCRIPTOR.message_types_by_name['ScenicObjectInfo'] = _SCENICOBJECTINFO
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ScenicObjectInfo = _reflection.GeneratedProtocolMessageType('ScenicObjectInfo', (_message.Message,), dict(
  DESCRIPTOR = _SCENICOBJECTINFO,
  __module__ = 'scenic_obj_info_pb2'
  # @@protoc_insertion_point(class_scope:scenic_obj_info_msgs.msgs.ScenicObjectInfo)
  ))
_sym_db.RegisterMessage(ScenicObjectInfo)


# @@protoc_insertion_point(module_scope)
